language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thomasarnold/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thomasarnold/docker-react npm run test